project:
  type: website
  output-dir: docs

website:
  title: "Eugene's Computer Science Journey"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/erabinov
      # - icon: twitter
        # href: https://twitter.com
format:
  html:
    theme: solar
    css: styles.css



